### ISSUE TITLE
evnotipi suddenly stopped working

### ISSUE THREAD

**Issue by FrenkK** [EVNotify/EVNotiPi#83]
Hello, not a Linux pro, so please excuse any rookie mistakes:
I had a working evnotipi install as per instructions here, only on RPi4 and I use it with web updates instead of Bluetooth. It is always on. The system worked for a week or so, but I had to turn off the Pi recently and now that it restarted, it stopped working. Tried restarting a few times and it doesn't help.
This is the system log excerpt:
```nov 10 10:39:54 PiCAN systemd[1]: Starting EVNotify Python Service...
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/SocketCAN:Initializing SocketCAN
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/EVNotify:Initializing EVNotify
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/EVNotify:Get settings from backend
nov 10 10:39:55 PiCAN systemd[1]: Started EVNotify Python Service.
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi:Starting main loop
nov 10 10:39:55 PiCAN evnotipi.py[989]: INFO:EVNotiPi/Car:NO DATA
nov 10 10:39:56 PiCAN evnotipi.py[989]: Exception in thread EVNotiPi/EVNotify:
nov 10 10:39:56 PiCAN evnotipi.py[989]: Traceback (most recent call last):
nov 10 10:39:56 PiCAN evnotipi.py[989]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
nov 10 10:39:56 PiCAN evnotipi.py[989]:     self.run()
nov 10 10:39:56 PiCAN evnotipi.py[989]:   File "/usr/lib/python3/dist-packages/gevent/threading.py", line 177, in run
nov 10 10:39:56 PiCAN evnotipi.py[989]:     super(Thread, self).run()
nov 10 10:39:56 PiCAN evnotipi.py[989]:   File "/usr/lib/python3.7/threading.py", line 865, in run
nov 10 10:39:56 PiCAN evnotipi.py[989]:     self._target(*self._args, **self._kwargs)
nov 10 10:39:56 PiCAN evnotipi.py[989]:   File "/opt/evnotipi/evnotify.py", line 165, in submit_data
nov 10 10:39:56 PiCAN evnotipi.py[989]:     if is_charging and now - last_evn_settings_poll > EVN_SETTINGS_INTERVAL:
nov 10 10:39:56 PiCAN evnotipi.py[989]: UnboundLocalError: local variable 'is_charging' referenced before assignment
nov 10 10:39:56 PiCAN evnotipi.py[989]: INFO:EVNotiPi/Car:NO DATA
nov 10 10:39:57 PiCAN evnotipi.py[989]: ERROR:EVNotiPi:Thread Failed (<evnotify.EVNotify object at 0xb55c9610>)
nov 10 10:39:57 PiCAN evnotipi.py[989]: INFO:EVNotiPi:Exiting ...
nov 10 10:39:58 PiCAN evnotipi.py[989]: INFO:EVNotiPi:Bye.
nov 10 10:39:58 PiCAN evnotipi.py[989]: Traceback (most recent call last):
nov 10 10:39:58 PiCAN evnotipi.py[989]:   File "/opt/evnotipi/evnotipi.py", line 130, in <module>
nov 10 10:39:58 PiCAN evnotipi.py[989]:     raise ThreadFailure(str(t))
nov 10 10:39:58 PiCAN evnotipi.py[989]: __main__.ThreadFailure: <evnotify.EVNotify object at 0xb55c9610>
nov 10 10:39:58 PiCAN systemd[1]: evnotipi.service: Main process exited, code=exited, status=1/FAILURE
nov 10 10:39:58 PiCAN systemd[1]: evnotipi.service: Failed with result 'exit-code'.
```
Do you have any idea what is wrong? The code and all packages are updated.

**Comment by FrenkK** [comment]
So... I was playing around and installed a GPS dongle. After configuring that properly, it works again.
By the way, I added a note in the install instructions that GPS dongles should be set up using gpsd. My first instinct was to do it in the config file.

**Comment by FrenkK** [comment]
The problem reocurred, so I set up debug logging and this is the result:
```
nov 10 13:38:25 PiCAN systemd[1]: Starting EVNotify Python Service...
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/SocketCAN:Initializing SocketCAN
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 7}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(7x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'SOC_BMS', 'width': 1, 'scale': 0.5}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 4}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(4x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'charging_bits1', 'width': 1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'dcBatteryCurrent', 'width': 2, 'signed': True, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(h)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'dcBatteryVoltage', 'width': 2, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(H)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'batteryMaxTemperature', 'width': 1, 'signed': True}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(b)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'batteryMinTemperature', 'width': 1, 'signed': True}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(b)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cellTemp%02d', 'idx': 1, 'cnt': 4, 'width': 1, 'signed': True}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(4b)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 2}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(2x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'batteryInletTemperature', 'width': 1, 'signed': True}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(b)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 6}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(6x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'auxBatteryVoltage', 'width': 1, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cumulativeChargeCurrent', 'width': 4, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(I)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cumulativeDischargeCurrent', 'width': 4, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(I)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cumulativeEnergyCharged', 'width': 4, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(I)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cumulativeEnergyDischarged', 'width': 4, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(I)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'operatingTime', 'width': 4}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(I)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'charging_bits2', 'width': 1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 8}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(8x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>7xB4xBhHbb4b2xb6xBIIIIIB8x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 7}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(7x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cellVoltage%02d', 'idx': 1, 'cnt': 32, 'width': 1, 'scale': 0.02}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>7x32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 7}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(7x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cellVoltage%02d', 'idx': 33, 'cnt': 32, 'width': 1, 'scale': 0.02}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>7x32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 7}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(7x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'cellVoltage%02d', 'idx': 65, 'cnt': 32, 'width': 1, 'scale': 0.02}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>7x32B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 28}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(28x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'soh', 'width': 2, 'scale': 0.1}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(H)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 4}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(4x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'SOC_DISPLAY', 'width': 1, 'scale': 0.5}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(B)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 11}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(11x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>28xH4xB11x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 9}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(9x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'name': 'odo', 'width': 3}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(BH)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:{'padding': 3}
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:field_fmt(3x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/ISO-TP-Decoder:fmt(>9xBH3x)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/EVNotify:Initializing EVNotify
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/SocketCAN:sendCommandEx_ISOTP cmd(220101) cantx(7ec) canrx(7e4)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/SocketCAN:canrx(0x7ec) cantx(0x7e4) cmd(220101)
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/EVNotify:Get settings from backend
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): app.evnotify.de:443
nov 10 13:38:26 PiCAN systemd[1]: Started EVNotify Python Service.
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi:Starting main loop
nov 10 13:38:26 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/Car:NO DATA
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:urllib3.connectionpool:https://app.evnotify.de:443 "GET /settings?akey=ff7e93&token=da826d7f79f83584ed0f HTTP/1.1" 200 None
nov 10 13:38:26 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/EVNotify:Waiting...
nov 10 13:38:27 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/EVNotify:Enqeue...
nov 10 13:38:27 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/EVNotify:Transmit...
nov 10 13:38:27 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/SocketCAN:sendCommandEx_ISOTP cmd(220101) cantx(7ec) canrx(7e4)
nov 10 13:38:27 PiCAN evnotipi.py[1094]: DEBUG:EVNotiPi/SocketCAN:canrx(0x7ec) cantx(0x7e4) cmd(220101)
nov 10 13:38:27 PiCAN evnotipi.py[1094]: DEBUG:urllib3.connectionpool:https://app.evnotify.de:443 "POST /location HTTP/1.1" 200 15
nov 10 13:38:27 PiCAN evnotipi.py[1094]: Exception in thread EVNotiPi/EVNotify:
nov 10 13:38:27 PiCAN evnotipi.py[1094]: Traceback (most recent call last):
nov 10 13:38:27 PiCAN evnotipi.py[1094]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
nov 10 13:38:27 PiCAN evnotipi.py[1094]:     self.run()
nov 10 13:38:27 PiCAN evnotipi.py[1094]:   File "/usr/lib/python3/dist-packages/gevent/threading.py", line 177, in run
nov 10 13:38:27 PiCAN evnotipi.py[1094]:     super(Thread, self).run()
nov 10 13:38:27 PiCAN evnotipi.py[1094]:   File "/usr/lib/python3.7/threading.py", line 865, in run
nov 10 13:38:27 PiCAN evnotipi.py[1094]:     self._target(*self._args, **self._kwargs)
nov 10 13:38:27 PiCAN evnotipi.py[1094]:   File "/opt/evnotipi/evnotify.py", line 165, in submit_data
nov 10 13:38:27 PiCAN evnotipi.py[1094]:     if is_charging and now - last_evn_settings_poll > EVN_SETTINGS_INTERVAL:
nov 10 13:38:27 PiCAN evnotipi.py[1094]: UnboundLocalError: local variable 'is_charging' referenced before assignment
nov 10 13:38:27 PiCAN evnotipi.py[1094]: INFO:EVNotiPi/Car:NO DATA
nov 10 13:38:28 PiCAN evnotipi.py[1094]: ERROR:EVNotiPi:Thread Failed (<evnotify.EVNotify object at 0xb560f570>)
nov 10 13:38:28 PiCAN evnotipi.py[1094]: INFO:EVNotiPi:Exiting ...
nov 10 13:38:29 PiCAN evnotipi.py[1094]: INFO:EVNotiPi:Bye.
nov 10 13:38:29 PiCAN evnotipi.py[1094]: Traceback (most recent call last):
nov 10 13:38:29 PiCAN evnotipi.py[1094]:   File "/opt/evnotipi/evnotipi.py", line 130, in <module>
nov 10 13:38:29 PiCAN evnotipi.py[1094]:     raise ThreadFailure(str(t))
nov 10 13:38:29 PiCAN evnotipi.py[1094]: __main__.ThreadFailure: <evnotify.EVNotify object at 0xb560f570>
nov 10 13:38:29 PiCAN systemd[1]: evnotipi.service: Main process exited, code=exited, status=1/FAILURE
nov 10 13:38:29 PiCAN systemd[1]: evnotipi.service: Failed with result 'exit-code'.
```
Please note this is with a "dormant" car, nothing is happening, it is off locked, not charging. Possibly this has something to do with the problem.

**Comment by FrenkK** [comment]
For some additional info: I have a Kona EV and this car has a "firewall", there is no bus traffic until you turn it on or actually make an active readout. I think the problem is related to this. I think that, as the program starts up, it assumes traffic, but there isn't any, so the "is_charging" variable never gets set before it is called.

**Comment by GPlay97** [comment]
Thank you for the hints. Can you pull the from latest master branch and give feedback if it still exists?

**Comment by FrenkK** [comment]
As far as I can see, nothing has changed, here is the system log:
```nov 12 14:39:55 PiCAN systemd[1]: Starting EVNotify Python Service...
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/SocketCAN:Initializing SocketCAN
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/SocketCAN:using ISO-TP support
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/EVNotify:Initializing EVNotify
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/EVNotify:Get settings from backend
nov 12 14:39:56 PiCAN systemd[1]: Started EVNotify Python Service.
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi:Starting main loop
nov 12 14:39:56 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/Car:NO DATA
nov 12 14:39:57 PiCAN evnotipi.py[1814]: Exception in thread EVNotiPi/EVNotify:
nov 12 14:39:57 PiCAN evnotipi.py[1814]: Traceback (most recent call last):
nov 12 14:39:57 PiCAN evnotipi.py[1814]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
nov 12 14:39:57 PiCAN evnotipi.py[1814]:     self.run()
nov 12 14:39:57 PiCAN evnotipi.py[1814]:   File "/usr/lib/python3/dist-packages/gevent/threading.py", line 177, in run
nov 12 14:39:57 PiCAN evnotipi.py[1814]:     super(Thread, self).run()
nov 12 14:39:57 PiCAN evnotipi.py[1814]:   File "/usr/lib/python3.7/threading.py", line 865, in run
nov 12 14:39:57 PiCAN evnotipi.py[1814]:     self._target(*self._args, **self._kwargs)
nov 12 14:39:57 PiCAN evnotipi.py[1814]:   File "/opt/evnotipi/evnotify.py", line 162, in submit_data
nov 12 14:39:57 PiCAN evnotipi.py[1814]:     if is_charging and now - last_evn_settings_poll > EVN_SETTINGS_INTERVAL:
nov 12 14:39:57 PiCAN evnotipi.py[1814]: UnboundLocalError: local variable 'is_charging' referenced before assignment
nov 12 14:39:57 PiCAN evnotipi.py[1814]: INFO:EVNotiPi/Car:NO DATA
nov 12 14:39:58 PiCAN evnotipi.py[1814]: ERROR:EVNotiPi:Thread Failed (<evnotify.EVNotify object at 0xb560a550>)
nov 12 14:39:58 PiCAN evnotipi.py[1814]: INFO:EVNotiPi:Exiting ...
nov 12 14:39:59 PiCAN evnotipi.py[1814]: INFO:EVNotiPi:Bye.
nov 12 14:39:59 PiCAN evnotipi.py[1814]: Traceback (most recent call last):
nov 12 14:39:59 PiCAN evnotipi.py[1814]:   File "/opt/evnotipi/evnotipi.py", line 130, in <module>
nov 12 14:39:59 PiCAN evnotipi.py[1814]:     raise ThreadFailure(str(t))
nov 12 14:39:59 PiCAN evnotipi.py[1814]: __main__.ThreadFailure: <evnotify.EVNotify object at 0xb560a550>
nov 12 14:39:59 PiCAN systemd[1]: evnotipi.service: Main process exited, code=exited, status=1/FAILURE
nov 12 14:39:59 PiCAN systemd[1]: evnotipi.service: Failed with result 'exit-code'.
nov 12 14:40:04 PiCAN systemd[1]: evnotipi.service: Service RestartSec=5s expired, scheduling restart.
nov 12 14:40:04 PiCAN systemd[1]: evnotipi.service: Scheduled restart job, restart counter is at 67.
nov 12 14:40:04 PiCAN systemd[1]: Stopped EVNotify Python Service.
```
Hopefully I updated correctly: I went to the home dir and did the `sudo git pull`. There were some updates. Then I restarted the service with `sudo systemctl restart evnotipi.service`. With no change, I also tried the `sudo systemctl disable evnotipi_shutdown.{timer,service}` as mentioned in the install instructions and then reenabled the service again.

**Comment by noradtux** [comment]
This issue should be fixed now.

**Comment by FrenkK** [comment]
I don't see an update on the git?

**Comment by FrenkK** [comment]
It does look like the issue is fixed now. I'm not sure why it took a while to happen, but it's probably something stupid I did ;)
Thank you!
